# Generated by Django 2.2.24 on 2022-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
