# Generated by Django 2.2.24 on 2022-03-07 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_author_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('link_git', models.URLField()),
                ('descriptions', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to='authors.Author')),
            ],
        ),
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('todo_descriptions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ProjectModel')),
            ],
        ),
    ]
