# Generated by Django 2.2.24 on 2022-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='todo_set',
            field=models.ManyToManyField(to='todo.TodoModel'),
        ),
    ]
