# Generated by Django 2.2.24 on 2022-03-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_position'),
        ('todo', '0002_projectmodel_todo_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Author'),
        ),
    ]
