# Generated by Django 2.2.24 on 2022-03-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todomodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='todo_set',
        ),
    ]
